// Generated by Protect-ShopResources.ps1. No signing private key is included.
// An offline client necessarily contains decryption material; the signature detects resource tampering.
namespace Shunshou.Core;
internal static class ShopResourceKeys
{
    internal const string PublicKey = "MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEA7xdqFfcZuN9ik5UkmLRTNhXsj/lWCWf9/k/wKuaz5l1D/IS+2FcueWL4V/ptnB63LNI37vPYpKyVeQsujO63HlMgR1acC5dSTEh993stETJvRL/u3LFIecgnnl/XYv8eC3WKYacmkZbui2ETDnUaK3imOD8mNASJi725mNShqFKupXGsUrFYYiMzZtwwwa2pmc3YvYDnr5lEVTR5WuqZLPc16xLFmziDTcRX25rf4Yg0TOVRrvzmG6Yh8gFUvz+/0HObH51DQ/e4fgw+BraOioniqFu/QZYbYwCHfwwBt6M2YdBnaGBIlCXfZi4I/ORrVjW1nYyeR4SVybHb7FOcY7kRVlLXxljg0dJbSYw7TjrSHBurM/TS68fOtEtRMG50GfFazz5qdzyQ9j+eE9Ckhwg1tx8pa/ycx4wDyDJruoLDMN6pLeH4Qpm5qgoBSnRVmARVO1fcN/EWOwK+a1JBB2jGE6RFxlouCi8EPc7g9y2AeRizWSiu4kkob7oGBGvtAgMBAAE=";
    internal const string DecryptionKey = "+sGgLEG7AYj6NQwakph4nqIo16A+SN62PbxsF2nFhD4=";
    internal const string SimUriHash = "73F34B55930A6D82C369B9C48604F325FDB8595D3E66F1D5492D242596D31D46";
    internal const string MembershipUriHash = "1653BB5F04AF754C5D89A403F0D6D8193C891FD288AA688F37882C00BFA41E68";
}