param([string]$OutputPath = (Join-Path $PSScriptRoot '../src/Shunshou.App/ToolIconData.g.cs'))
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName PresentationCore
# Original 24-unit vector artwork. Widen round 1.4-unit strokes at build-authoring time
# because WinUI PathIcon accepts a filled geometry rather than a stroke.
$paths = [ordered]@{
  zip = 'M5,3 H15 L20,8 V21 H5 Z M15,3 V8 H20 M10,3 V5 M10,7 V9 M10,11 V13 M9,15 H11 V18 H9 Z'
  pdf = 'M5,3 H15 L20,8 V21 H5 Z M15,3 V8 H20 M8,12 H16 M8,15 H16 M8,18 H13'
  image = 'M3,5 H21 V19 H3 Z M4,17 L9,12 L13,16 L16,13 L20,17 M14,8 A1,1 0 1 1 14,10 A1,1 0 1 1 14,8'
  media = 'M3,4 H18 V15 H3 Z M8,7 L13,9.5 L8,12 Z M19,12 V19 M19,12 L22,11 V17 M19,19 C19,21 15,21 15,19 C15,17 19,17 19,19 M22,17 C22,19 19,19 19,17 C19,15 22,15 22,17'
  search = 'M3,18 V5 H10 L12,8 H21 V11 M3,18 H9 M14,12 A4,4 0 1 1 14,20 A4,4 0 1 1 14,12 M17,19 L21,23'
  uninstall = 'M3,4 H21 V20 H3 Z M3,8 H21 M6,6 H6.2 M9,6 H9.2 M8,14 H16'
  shop = 'M4,9 V21 H20 V9 M8,21 V14 H13 V21 M3,9 L5,3 H19 L21,9 M3,9 C3,13 7.5,13 7.5,9 M7.5,9 C7.5,13 12,13 12,9 M12,9 C12,13 16.5,13 16.5,9 M16.5,9 C16.5,13 21,13 21,9'
  recovery = 'M3,18 V5 H10 L12,8 H21 V18 H16 M8,21 A6,6 0 1 0 8,11 M8,11 L4,11 L4,7 M8,11 L5,14'
  ocr = 'M3,8 V3 H8 M16,3 H21 V8 M21,16 V21 H16 M8,21 H3 V16 M8,17 L12,7 L16,17 M10,13 H14'
  download = 'M12,3 V15 M7,10 L12,15 L17,10 M4,15 V21 H20 V15'
  upload = 'M5,3 H15 L20,8 V11 M5,3 V21 H10 M15,3 V8 H20 M16,22 V13 M12,17 L16,13 L20,17'
  watermark = 'M4,7 H19 V20 H4 Z M7,4 H21 V17 M9,15 L13,11 M9,11 L13,15 M17,3 V7 M15,5 H19'
  headset = 'M4,13 V10 A8,8 0 0 1 20,10 V17 C20,20 17,21 14,21 M4,11 H7 V17 H4 Z M17,11 H20 V17 H17 Z M12,21 H14'
  sun = 'M12,7 A5,5 0 1 1 12,17 A5,5 0 1 1 12,7 M12,1 V3 M12,21 V23 M1,12 H3 M21,12 H23 M4,4 L5.5,5.5 M18.5,18.5 L20,20 M4,20 L5.5,18.5 M18.5,5.5 L20,4'
  moon = 'M19.5,15.8 A8.5,8.5 0 1 1 8.2,4.5 A7,7 0 0 0 19.5,15.8 Z'
  sim = 'M6,3 H14 L19,8 V21 H6 Z M9,11 H16 V18 H9 Z M9,14.5 H16 M12.5,11 V18'
  coupon = 'M3,6 H21 V10 C18,10 18,14 21,14 V18 H3 V14 C6,14 6,10 3,10 Z M12,9 L12.8,11 H15 L13.2,12.5 L14,14.5 L12,13.2 L10,14.5 L10.8,12.5 L9,11 H11.2 Z'
  external = 'M13,3 H21 V11 M21,3 L11,13 M9,5 H4 V20 H19 V15'
  check = 'M5,12 L10,17 L20,6'
}
$pen = [System.Windows.Media.Pen]::new([System.Windows.Media.Brushes]::Black, 1.4)
$pen.StartLineCap = 'Round'
$pen.EndLineCap = 'Round'
$pen.LineJoin = 'Round'
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// Generated by scripts/Generate-ToolIcons.ps1; original rounded outline artwork.')
$lines.Add('namespace Shunshou.App;')
$lines.Add('internal static class ToolIconData')
$lines.Add('{')
$lines.Add('    internal static readonly IReadOnlyDictionary<string, string> Paths = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)')
$lines.Add('    {')
foreach ($entry in $paths.GetEnumerator()) {
    $geometry = [System.Windows.Media.Geometry]::Parse($entry.Value).GetWidenedPathGeometry($pen)
    $data = $geometry.ToString([System.Globalization.CultureInfo]::InvariantCulture)
    $data = [regex]::Replace($data, '-?\d+\.\d+', { param($m) ([double]::Parse($m.Value, [System.Globalization.CultureInfo]::InvariantCulture)).ToString('0.###', [System.Globalization.CultureInfo]::InvariantCulture) })
    $lines.Add('        ["' + $entry.Key + '"] = "' + $data + '",')
}
$lines.Add('    };')
$lines.Add('}')
[System.IO.File]::WriteAllLines([System.IO.Path]::GetFullPath($OutputPath), $lines, [System.Text.UTF8Encoding]::new($false))
