param(
    [Parameter(Mandatory = $true)][string]$QrImagePath,
    [Parameter(Mandatory = $true)][uri]$SimStoreUri,
    [Parameter(Mandatory = $true)][uri]$MembershipStoreUri
)
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$privateDirectory = Join-Path $repoRoot '.tools/private-shop'
$privateKeyPath = Join-Path $privateDirectory 'shop-signing-key.pk8'
$symmetricKeyPath = Join-Path $privateDirectory 'shop-encryption-key.bin'
$resourceDirectory = Join-Path $repoRoot 'src/Shunshou.Core/Resources'
$generatedKeyPath = Join-Path $repoRoot 'src/Shunshou.Core/ShopResourceKeys.g.cs'

foreach ($target in @(@($SimStoreUri, 'ym.ksjhaoka.com'), @($MembershipStoreUri, 'vip.ksjhaoka.com'))) {
    $uri = [uri]$target[0]
    if ($uri.Scheme -ne 'https' -or $uri.DnsSafeHost -cne $target[1] -or -not $uri.IsDefaultPort -or
        $uri.AbsolutePath -ne '/' -or $uri.UserInfo -or $uri.Fragment) { throw 'Unsupported shop address.' }
}
$qrBytes = [IO.File]::ReadAllBytes((Resolve-Path -LiteralPath $QrImagePath).Path)
if ($qrBytes.Length -lt 24 -or $qrBytes.Length -gt 8MB -or
    [Convert]::ToHexString($qrBytes[0..7]) -ne '89504E470D0A1A0A' -or
    [Convert]::ToHexString($qrBytes[16..23]) -ne '0000030800000308') {
    throw 'Expected a tightly cropped 776x776 PNG QR image supplied by the owner.'
}
[IO.Directory]::CreateDirectory($privateDirectory) | Out-Null
[IO.Directory]::CreateDirectory($resourceDirectory) | Out-Null
$rsa = [Security.Cryptography.RSA]::Create(3072)
try {
    if (Test-Path -LiteralPath $privateKeyPath) {
        $read = 0
        $rsa.ImportPkcs8PrivateKey([IO.File]::ReadAllBytes($privateKeyPath), [ref]$read)
        if ($rsa.KeySize -ne 3072) { throw 'Expected a 3072-bit signing key.' }
    } else {
        if (Test-Path -LiteralPath $generatedKeyPath) {
            throw 'Signing key is missing. Restore the original private key; automatic key replacement is disabled.'
        }
        [IO.File]::WriteAllBytes($privateKeyPath, $rsa.ExportPkcs8PrivateKey())
    }
    if (Test-Path -LiteralPath $symmetricKeyPath) {
        $aesKey = [IO.File]::ReadAllBytes($symmetricKeyPath)
    } else {
        $aesKey = [Security.Cryptography.RandomNumberGenerator]::GetBytes(32)
        [IO.File]::WriteAllBytes($symmetricKeyPath, $aesKey)
    }
    if ($aesKey.Length -ne 32) { throw 'Expected a 256-bit encryption key.' }
    $simBytes = [Text.Encoding]::UTF8.GetBytes($SimStoreUri.OriginalString)
    $membershipBytes = [Text.Encoding]::UTF8.GetBytes($MembershipStoreUri.OriginalString)
    $payload = [IO.MemoryStream]::new()
    $writer = [IO.BinaryWriter]::new($payload)
    $writer.Write([int]$simBytes.Length); $writer.Write([byte[]]$simBytes)
    $writer.Write([int]$membershipBytes.Length); $writer.Write([byte[]]$membershipBytes)
    $writer.Write([int]$qrBytes.Length); $writer.Write([byte[]]$qrBytes)
    $writer.Flush()
    $plaintext = $payload.ToArray()
    $nonce = [Security.Cryptography.RandomNumberGenerator]::GetBytes(12)
    $tag = [byte[]]::new(16)
    $ciphertext = [byte[]]::new($plaintext.Length)
    $prefix = [byte[]]([Text.Encoding]::ASCII.GetBytes('SHTSHOP1') + [BitConverter]::GetBytes([int]1))
    $aes = [Security.Cryptography.AesGcm]::new($aesKey, 16)
    try { $aes.Encrypt($nonce, $plaintext, $ciphertext, $tag, $prefix) } finally { $aes.Dispose() }
    $signedBytes = [byte[]]($prefix + $nonce + $tag + [BitConverter]::GetBytes([int]$ciphertext.Length) + $ciphertext)
    $signature = $rsa.SignData($signedBytes, [Security.Cryptography.HashAlgorithmName]::SHA256, [Security.Cryptography.RSASignaturePadding]::Pss)
    $resourcePath = Join-Path $resourceDirectory 'ShopResources.bin'
    [IO.File]::WriteAllBytes($resourcePath, [byte[]]($signedBytes + $signature))
    $publicKey = [Convert]::ToBase64String($rsa.ExportSubjectPublicKeyInfo())
    $keyText = [Convert]::ToBase64String($aesKey)
    $simHash = [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($simBytes))
    $membershipHash = [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($membershipBytes))
    $source = @"
// Generated by Protect-ShopResources.ps1. No signing private key is included.
// An offline client necessarily contains decryption material; the signature detects resource tampering.
namespace Shunshou.Core;
internal static class ShopResourceKeys
{
    internal const string PublicKey = "$publicKey";
    internal const string DecryptionKey = "$keyText";
    internal const string SimUriHash = "$simHash";
    internal const string MembershipUriHash = "$membershipHash";
}
"@
    [IO.File]::WriteAllText($generatedKeyPath, $source, [Text.UTF8Encoding]::new($false))
    Write-Output 'Protected shop resource generated. The signing private key stays in .tools/private-shop.'
} finally {
    if ($plaintext) { [Security.Cryptography.CryptographicOperations]::ZeroMemory($plaintext) }
    if ($aesKey) { [Security.Cryptography.CryptographicOperations]::ZeroMemory($aesKey) }
    if ($writer) { $writer.Dispose() }
    if ($payload) { $payload.Dispose() }
    $rsa.Dispose()
}
